# Javascript Node CircleCI 2.0 configuration file
#
# NOTE: successful build commits to the $SMU_DEPLOY_BRANCH var below will deploy
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.1

    working_directory: ~/code

    environment:
      SMU_AWS_S3_BUCKET_NAME: smutil.com
      SMU_BUILD_DIR: ~/code/smutil/build
      SMU_DEPLOY_BRANCH: stable

    steps:
      - run:
          # TODO: consider caching apt images or custom docker image
          name: Install Environment Dependencies
          command: |
            sudo apt update
            sudo apt install python python-dev python-pip
            sudo pip install awscli

      - checkout

      - restore_cache:
          name: Restore Yarn package cache
          keys:
          - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Yarn Packages
          command: yarn install --ignore-engines

      - save_cache:
          name: Save Yarn package cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - node_modules

      - run:
          name: Build SMUtil
          command: yarn build

      # TODO!
      # run tests!
      #- run: yarn test

      # TODO: smarter cache invalidation, only changed files?
      - deploy:
          name: Deploy to AWS
          command: |
            if [ "${CIRCLE_BRANCH}" = $SMU_DEPLOY_BRANCH ]; then
              aws s3 sync build/ s3://$SMU_AWS_S3_BUCKET_NAME/ --delete
              aws cloudfront create-invalidation --distribution-id $SMU_AWS_CLOUDFRONT_ID --paths /\* /\*/\*
            else
              echo "Not '$SMU_DEPLOY_BRANCH' branch, build only (no deploy)"
            fi
