version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.0

defaults:
  &defaults
  docker:
    - image: cimg/node:18.18
  environment:
    SMU_AWS_S3_BUCKET_NAME: smutil.com
  resource_class: large
  working_directory: /code

jobs:
  build:
    <<: *defaults
    steps:
      - run: mkdir smutil && cd smutil
      - checkout
      - restore_cache:
          name: Restore Yarn package cache
          keys:
          - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Yarn Packages
          command: yarn install --ignore-engines
      - save_cache:
          name: Save Yarn package cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - node_modules
      - run:
          name: Build
          command: yarn build
      - persist_to_workspace:
          root: smutil
          paths:
            - build
  deploy:
    <<: *defaults
    steps:
      - aws-cli/setup
      - run: pwd
      - run: ls -lah
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /code/smutil
      - deploy:
          name: Deploy to AWS
          # TODO: smarter cache invalidation, only changed files?
          command: |
            echo ":: deploying to: $SMU_AWS_S3_BUCKET_NAME"
            aws s3 sync ./build/ s3://$SMU_AWS_S3_BUCKET_NAME/ --delete
            echo ":: invalidating cache: $SMU_AWS_CLOUDFRONT_ID"
            aws cloudfront create-invalidation --distribution-id $SMU_AWS_CLOUDFRONT_ID --paths / /\* /\*/\*

workflows:
  build:
    jobs:
      - build
      - deploy:
          context:
            - askhr-apps-deployer
          requires:
            - build
          # filters:
          #   branches:
          #     only: stable
