# Javascript Node CircleCI 2.1 configuration file
#
# NOTE: successful build commits to the $SMU_DEPLOY_BRANCH var below will deploy
#
version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.0

defaults:
  &defaults
  docker:
    - image: cimg/node:18.18
  environment:
    SMU_AWS_S3_BUCKET_NAME: smutil.com
    SMU_BUILD_DIR: ~/code/smutil/build
    SMU_DEPLOY_BRANCH: stable
  resource_class: large

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn package cache
          keys:
          - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Yarn Packages
          command: yarn install --ignore-engines
      - save_cache:
          name: Save Yarn package cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - node_modules
      - run:
          name: Build
          command: yarn build
      # TODO: run tests!
  deploy:
    <<: *defaults
    steps:
      - aws-cli/setup
      - deploy:
          name: Deploy to AWS
          # TODO: smarter cache invalidation, only changed files?
          command: |
            if [ "${CIRCLE_BRANCH}" = $SMU_DEPLOY_BRANCH ]; then
              echo ":: deploying to: $SMU_AWS_S3_BUCKET_NAME"
              aws s3 sync build/ s3://$SMU_AWS_S3_BUCKET_NAME/ --delete
              echo ":: invalidating cache: $SMU_AWS_CLOUDFRONT_ID"
              aws cloudfront create-invalidation --distribution-id $SMU_AWS_CLOUDFRONT_ID --paths / /\* /\*/\*
            else
              echo "Not '$SMU_DEPLOY_BRANCH' branch, build only (no deploy)"
            fi

workflows:
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build
          context:
            - askhr-apps-deployer
