name: Main

# See: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions
on:
  push:
    branches:
      - '**'
  workflow_dispatch:

# The `concurrency` key ensures that only a single workflow in the same concurrency group will run at the same time
concurrency:
    group: '${{ github.workflow }}@${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
    cancel-in-progress: true

env:
  AWS_REGION: us-east-1
  S3_BUCKET_NAME: smutil.com

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:18
    env:
      NODE_ENV: development
    steps:
      - uses: actions/checkout@v4
      # - uses: actions/setup-node@v4
      #   with:
      #     # node-version: 18
      #     node-version-file: .nvmrc
      #     check-latest: true
      - uses: actions/cache@v4
        id: cache-modules
        with:
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
          path: node_modules
      - name: Node version
        run: node --version
      - name: Yarn install
        run: yarn install --ignore-engines
      - name: Yarn build
        run: yarn build
      - uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: ./build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build-output
          path: ./build
      - run: ls -lah
