name: Main

# See: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions
on:
  push:
    branches:
      - "**"
  workflow_dispatch:

# The `concurrency` key ensures that only a single workflow in the same concurrency group will run at the same time
concurrency:
  group: "${{ github.workflow }}@${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

env:
  AWS_REGION: us-east-1
  BUILD_DIR: ./build
  CLOUDFRONT_ID: E1BHSB1SPTRYVA
  NODE_ENV: development
  S3_BUCKET_NAME: smutil.com

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          # node-version: 18
          node-version-file: .nvmrc
          check-latest: true
      - uses: actions/cache@v4
        id: cache-modules
        with:
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
          path: node_modules
      - name: Node version
        run: node --version
      - name: Yarn install
        run: yarn install --ignore-engines
      - name: Yarn build
        env:
          NODE_ENV: production
        run: yarn build
      - uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: ${{ env.BUILD_DIR }}

  deploy:
    # github.ref == 'refs/heads/main'
    if: github.ref_name == github.event.repository.default_branch
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          # aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - run: aws --version
      - run: aws sts get-caller-identity
      - uses: actions/download-artifact@v4
        with:
          name: build-output
          path: ${{ env.BUILD_DIR }}
      # TODO: Configure AWS OIDC integration instead of CLI credentials
      # See https://github.com/marketplace/actions/configure-aws-credentials-action-for-github-actions
      - name: Deploy to AWS
        run: |
          echo ":: deploying to: ${{ env.S3_BUCKET_NAME }}"
          aws s3 sync ${{ env.BUILD_DIR }}/ s3://${{ env.S3_BUCKET_NAME }}/ --delete

          echo ":: invalidating cache: ${{ env.CLOUDFRONT_ID }}"
          aws cloudfront create-invalidation --distribution-id ${{ env.CLOUDFRONT_ID }} --paths / /\* /\*/\*
