name: Main

# See: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions
on:
  push:
    branches:
      - "**"
  workflow_dispatch:

# The `concurrency` key ensures that only a single workflow in the same concurrency group will run at the same time
concurrency:
  group: "${{ github.workflow }}@${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

env:
  AWS_REGION: us-east-1
  BUILD_DIR: ./build
  CLOUDFRONT_ID: E1BHSB1SPTRYVA
  NODE_ENV: development
  S3_BUCKET_NAME: smutil.com

# Permission can be added at job level or workflow level
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          # Note: Don't set node-version and node-version-file together
          # node-version: 24
          node-version-file: .nvmrc
          check-latest: true
      - uses: actions/cache@v5
        id: cache-modules
        with:
          key: ${{ runner.os }}-modules-${{ hashFiles('package-lock.json') }}
          path: node_modules
      - name: npm install
        run: npm ci
      - name: npm build
        env:
          NODE_ENV: production
        run: npm run build
      - uses: actions/upload-artifact@v7
        with:
          name: build-output
          path: ${{ env.BUILD_DIR }}

  deploy:
    # github.ref == 'refs/heads/main'
    if: github.ref_name == github.event.repository.default_branch
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::881242931272:role/gh-actions-smutil
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      - uses: actions/download-artifact@v8
        with:
          name: build-output
          path: ${{ env.BUILD_DIR }}
      # Uses AWS OIDC integration instead of CLI credentials
      # See https://github.com/marketplace/actions/configure-aws-credentials-action-for-github-actions
      - name: Deploy to AWS
        run: |
          echo ":: deploying to: ${{ env.S3_BUCKET_NAME }}"
          aws s3 sync ${{ env.BUILD_DIR }}/ s3://${{ env.S3_BUCKET_NAME }}/ --delete

          echo ":: invalidating cache: ${{ env.CLOUDFRONT_ID }}"
          aws cloudfront create-invalidation --distribution-id ${{ env.CLOUDFRONT_ID }} --paths / /\* /\*/\*
